name: Ubuntu.20.04

on: workflow_dispatch

jobs:
  build:
  

    runs-on: Ubuntu.20.04


    steps:
    - name: sudo update
      run: sudo apt update -y && sudo apt upgrade -y
    - name: instalando Ubuntu desktop
      run: |
        sudo useradd -m expedito && sudo adduser expedit sudo && echo 'expedito:expedit' | sudo chpasswd
        
        sudo apt install ubuntu-desktop xfce4 xrdp -y

    - name: configurando
      run: |
         sudo wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
         unzip ngrok-stable-linux-amd64.zip
         echo xfce4-session >~/.xsession
         sudo service xrdp start
         sudo ./ngrok authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

         - name: Abrindo Porta 3389
         run: |
         sudo ./ngrok tcp 3389
