name: UBUNTU 20.04

on:

  push:

  jobs:
    runs-on: ubuntu-20.04

    -uses: actions/checkout@v2
      
      - name: Update
      run: sudo apt update -y && sudo apt upgrade -y

      - name: Instalando o ubuntu desktop
        run: |
        sudo useradd -m expedito && sudo adduser expedit sudo && echo 'expedito:expedit' | sudo chpasswd
        
        sudo apt install ubuntu-desktop xfce4 xrdp -y

      - name: Configurando tudo
        run: |
         sudo wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
         unzip ngrok-stable-linux-amd64.zip
         echo xfce4-session >~/.xsession
         sudo service xrdp start
         sudo ./ngrok authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

         - name: Abrindo Porta 3389
         run: |
         sudo ./ngrok tcp 3389
